export const strings = {
  common: {
    appName: 'InFinance',
    loading: 'Cargando...',
    retry: 'Reintentar',
    cancel: 'Cancelar',
    save: 'Guardar',
    delete: 'Eliminar',
    edit: 'Editar',
    create: 'Crear',
    search: 'Buscar',
    empty: 'No hay datos disponibles.',
    notAvailable: '—',
    detailSeparator: '·',
    unknownError: 'No se pudo completar la operación.',
    networkError: 'No se pudo conectar con el servidor.',
    timeoutError: 'La solicitud tardó demasiado.',
    authorizationError: 'No tienes permisos para realizar esta acción.',
    notFoundError: 'No se encontró el recurso solicitado.',
    notFoundTitle: 'Página no encontrada',
    backToHome: 'Volver al inicio',
    serverError: 'El servidor no pudo completar la solicitud.',
  },
  auth: {
    loginTitle: 'Bienvenido de nuevo',
    loginSubtitle: 'Consulta tus activos y alertas desde un solo lugar.',
    registerTitle: 'Crea tu cuenta',
    registerSubtitle: 'Empieza a seguir el mercado con InFinance.',
    email: 'Correo electrónico',
    password: 'Contraseña',
    confirmPassword: 'Confirmar contraseña',
    login: 'Iniciar sesión',
    register: 'Crear cuenta',
    logout: 'Cerrar sesión',
    goToRegister: '¿No tienes cuenta? Regístrate',
    goToLogin: '¿Ya tienes cuenta? Inicia sesión',
    sessionExpired: 'Tu sesión ha expirado.',
    passwordMismatch: 'Las contraseñas no coinciden.',
    invalidEmail: 'Introduce un correo válido.',
    shortPassword: 'La contraseña debe tener al menos 6 caracteres.',
    unavailable: 'Configura Supabase en .env para habilitar la autenticación.',
    loginFailed: 'No se pudo iniciar sesión.',
    confirmEmail: 'Revisa tu correo para confirmar la cuenta.',
  },
  navigation: {
    market: 'Mercado',
    watchlists: 'Listas',
    alerts: 'Alertas',
    notifications: 'Avisos',
    profile: 'Perfil',
  },
  market: {
    title: 'Mercado',
    subtitle: 'Activos disponibles',
    searchPlaceholder: 'Buscar símbolo o nombre',
    all: 'Todos',
    typeLabels: {
      stock: 'Acciones',
      crypto: 'Cripto',
      forex: 'Forex',
      index: 'Índices',
    },
    livePrice: 'Precio actual',
    currencySymbol: '$',
    assetNotFound: 'No se encontró el activo solicitado.',
    chartUnavailableLabel: 'Gráfico de precio no disponible',
    unavailableHistory: 'El histórico aún no está disponible en la API.',
  },
  charts: {
    accessibilityLabel: 'Gráfico de precios históricos',
    empty: 'No hay precios históricos para este intervalo.',
    selectedInterval: (interval: string) => `Intervalo ${interval} seleccionado`,
  },
  watchlists: {
    title: 'Mis listas',
    create: 'Nueva lista',
    namePlaceholder: 'Nombre de la lista',
    empty: 'Todavía no tienes listas de seguimiento.',
    assets: 'Activos de la lista',
    availableAssets: 'Añadir activos',
    removeAsset: 'Quitar',
    addAsset: 'Añadir',
    emptyAssets: 'Esta lista todavía no contiene activos.',
    requiredName: 'El nombre de la lista es obligatorio.',
    notFound: 'No se encontró la lista solicitada.',
    assetCount: (count: number) =>
      `${count} ${count === 1 ? 'activo' : 'activos'}`,
  },
  alerts: {
    title: 'Alertas',
    create: 'Nueva alerta',
    empty: 'No tienes alertas configuradas.',
    history: 'Historial',
    historyEmpty: 'Todavía no hay alertas disparadas.',
    assetFilter: 'ID del activo',
    dateFrom: 'Desde (AAAA-MM-DD)',
    dateTo: 'Hasta (AAAA-MM-DD)',
    allStatuses: 'Todos',
    triggeredPrice: 'Precio disparado',
    asset: 'Activo',
    target: 'Valor objetivo',
    condition: 'Condición',
    above: 'Por encima',
    below: 'Por debajo',
    active: 'Activa',
    inactive: 'Pausada',
    enable: 'Activar',
    pause: 'Pausar',
    assetRequired: 'Selecciona un activo.',
    negativeTarget: 'El valor objetivo no puede ser negativo.',
    invalidTarget: 'Introduce un valor objetivo válido.',
    conditionRequired: 'Selecciona una condición.',
    typeLabels: {
      price_target: 'Precio objetivo',
      percent_variation: 'Variación porcentual',
      indicator: 'Indicador',
      dividend: 'Dividendo',
    },
    conditionLabels: {
      above: 'Por encima',
      below: 'Por debajo',
      crosses_up: 'Cruza hacia arriba',
      crosses_down: 'Cruza hacia abajo',
    },
  },
  notifications: {
    title: 'Notificaciones',
    empty: 'No tienes notificaciones.',
    markRead: 'Marcar como leída',
    read: 'Leída',
    unread: 'Nueva',
    all: 'Todas',
    onlyUnread: 'No leídas',
  },
  profile: {
    title: 'Perfil',
    appearance: 'Apariencia',
    system: 'Sistema',
    light: 'Claro',
    dark: 'Oscuro',
    userId: 'ID de usuario',
    userIdValue: (userId: string) => `ID de usuario: ${userId}`,
  },
} as const;
